export enum EOrderSituation {
    ORDER_PAYMENT_PENDING = 'ORDER_PAYMENT_PENDING',
    ORDER_PAYMENT_COMPLETED = 'ORDER_PAYMENT_COMPLETED',
    ORDER_IN_PREPARE = 'ORDER_IN_PREPARE',
    ORDER_BEING_SHIPPED = 'ORDER_BEING_SHIPPED',
    ORDER_SHIPPED = 'ORDER_SHIPPED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',
    ORDER_RETURNED = 'ORDER_RETURNED',
}